# Generated by Django 4.2.7 on 2023-12-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='type',
            field=models.CharField(choices=[('grassland', '草地'), ('hardfloor', '硬地'), ('muddyroad', '泥地'), ('carpet', '地毯')], default='grassland', max_length=255),
        ),
    ]
