# Generated by Django 4.2.7 on 2023-12-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_court_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
